// apps/playground-nuxt/app/components/DatePickerDemo.vue
<script setup lang="ts">
import { DatePicker } from '@jalali-js/vue';
import type { StorageValue } from 'jalali-js';
import { ref } from 'vue';

const stored = ref<StorageValue>();
</script>

<template>
  <div>
    <DatePicker v-model="stored" system="jalali" locale="en" />
    <p data-testid="stored-value">Stored value: {{ JSON.stringify(stored) }}</p>
  </div>
</template>

// apps/playground-next/app/date-picker-demo.tsx
'use client';

import { DatePicker } from '@jalali-js/react';
import type { StorageValue } from 'jalali-js';
import { useState } from 'react';

export function DatePickerDemo() {
  const [stored, setStored] = useState<StorageValue | null>(null);
  return (
    <div>
      <DatePicker system="jalali" locale="en" onChange={(value) => setStored(value)} />
      <p data-testid="stored-value">Stored value: {JSON.stringify(stored)}</p>
    </div>
  );
}
