// packages/vue/src/Calendar.vue
<script setup lang="ts">
/**
 * A headless month grid: it renders plain markup with data attributes (`data-selected`,
 * `data-today`, `data-outside-month`, `data-disabled`, `data-holiday`) and no required CSS, so a
 * consumer can restyle it completely. A `day` scoped slot lets a consumer replace the cell
 * markup outright while keeping the grid and header structure. `DatePicker` is this same
 * component with a default stylesheet and a popover wrapped around it.
 *
 * Days blocked by `rules` render as disabled buttons: clicks do nothing and the Tab order
 * skips them, so keyboard navigation skips blocked days. With `showHolidays`, holiday days
 * get `data-holiday`. With `blockHolidays`, those days also become unselectable.
 *
 * With `quickNav` (default on), clicking the month or year in the header opens a month grid or
 * a year grid, so a person can jump years ahead without paging one month at a time. Picking a
 * year moves to the month grid; picking a month moves to the day grid.
 */
import { resolveCalendarHolidays, type HolidayRegion } from '@jalali-js/holidays';
import { format as formatDate, formatNumber } from '@jalali-js/i18n';
import type { CalendarDate, CalendarGridDay, CalendarSystem, SelectionRules } from 'jalali-js';
import {
  buildCalendarGrid,
  createCalendar,
  nextMonth,
  previousMonth,
  weekdayLabelsForGrid,
} from 'jalali-js';
import { computed, ref } from 'vue';
import { localePackFor, type LocaleCode } from './use-calendar.js';

const YEARS_PER_PAGE = 12;

function yearPageStart(year: number): number {
  return year - (((year % YEARS_PER_PAGE) + YEARS_PER_PAGE) % YEARS_PER_PAGE);
}

const props = withDefaults(
  defineProps<{
    system?: CalendarSystem;
    locale?: LocaleCode;
    value?: CalendarDate | null;
    initialDisplayedMonth?: { year: number; month: number };
    /** Let a person click the month or year in the header to jump straight to a month grid or
     * a year grid, instead of paging one month at a time. Default: true. */
    quickNav?: boolean;
    /** Limits on what a person can select (see `isDateSelectable()` in `jalali-js`). Blocked
     * days render disabled, with a `data-disabled` attribute, and reject selection. */
    rules?: SelectionRules | undefined;
    /** Mark official holidays with a `data-holiday` attribute. Jalali system only. Default: Iran. */
    showHolidays?: boolean;
    /** Also block holiday days through selection rules. Jalali system only. */
    blockHolidays?: boolean;
    /** Whose official holiday list to use. Default: `'IR'` (Iran). */
    holidayRegion?: HolidayRegion;
  }>(),
  {
    system: 'jalali',
    locale: 'en',
    value: null,
    quickNav: true,
    showHolidays: false,
    blockHolidays: false,
    holidayRegion: 'IR',
  },
);

const emit = defineEmits<{ select: [date: CalendarDate] }>();

const localePack = computed(() => localePackFor(props.locale));
const today = computed(() => createCalendar({ system: props.system }).today());
const displayed = ref(
  props.initialDisplayedMonth ??
    (props.value
      ? { year: props.value.year, month: props.value.month }
      : { year: today.value.year, month: today.value.month }),
);
const view = ref<'day' | 'month' | 'year'>('day');
const yearPage = ref(yearPageStart(displayed.value.year));

const holidayOptions = computed(() =>
  resolveCalendarHolidays(props.system, displayed.value.year, displayed.value.month, {
    showHolidays: props.showHolidays,
    blockHolidays: props.blockHolidays,
    region: props.holidayRegion,
    rules: props.rules,
  }),
);

const weeks = computed<CalendarGridDay[][]>(() =>
  buildCalendarGrid(
    props.system,
    displayed.value.year,
    displayed.value.month,
    today.value,
    props.value,
    holidayOptions.value.rules,
    holidayOptions.value.isHolidayDay,
  ),
);

const monthLabel = computed(
  () => localePack.value.monthNames[props.system].long[displayed.value.month - 1],
);
const yearLabel = computed(() =>
  formatNumber(displayed.value.year, localePack.value.defaultNumerals, localePack.value.digits),
);
const titleTag = computed(() => (props.quickNav ? 'button' : 'span'));
const yearPageLabel = computed(() => {
  const start = formatNumber(
    yearPage.value,
    localePack.value.defaultNumerals,
    localePack.value.digits,
  );
  const end = formatNumber(
    yearPage.value + YEARS_PER_PAGE - 1,
    localePack.value.defaultNumerals,
    localePack.value.digits,
  );
  return `${start} – ${end}`;
});
const months = computed(() =>
  localePack.value.monthNames[props.system].long.map((name, index) => {
    const month = index + 1;
    return {
      name,
      month,
      isSelected: displayed.value.month === month,
      isCurrent: today.value.year === displayed.value.year && today.value.month === month,
    };
  }),
);
const years = computed(() =>
  Array.from({ length: YEARS_PER_PAGE }, (_, index) => yearPage.value + index).map((year) => ({
    year,
    label: formatNumber(year, localePack.value.defaultNumerals, localePack.value.digits),
    isSelected: displayed.value.year === year,
    isCurrent: today.value.year === year,
  })),
);

function goNext(): void {
  displayed.value = nextMonth(props.system, displayed.value.year, displayed.value.month);
}
function goPrevious(): void {
  displayed.value = previousMonth(props.system, displayed.value.year, displayed.value.month);
}
function goNextYearInMonthView(): void {
  displayed.value = { ...displayed.value, year: displayed.value.year + 1 };
}
function goPreviousYearInMonthView(): void {
  displayed.value = { ...displayed.value, year: displayed.value.year - 1 };
}
function goNextYearPage(): void {
  yearPage.value += YEARS_PER_PAGE;
}
function goPreviousYearPage(): void {
  yearPage.value -= YEARS_PER_PAGE;
}
function openMonthView(): void {
  view.value = 'month';
}
function openYearView(): void {
  yearPage.value = yearPageStart(displayed.value.year);
  view.value = 'year';
}
function pickMonth(month: number): void {
  displayed.value = { ...displayed.value, month };
  view.value = 'day';
}
function pickYear(year: number): void {
  displayed.value = { ...displayed.value, year };
  view.value = 'month';
}
function selectDay(date: CalendarDate): void {
  emit('select', date);
}
function dayLabel(cell: CalendarGridDay): string {
  return formatDate(cell.date, localePack.value, { style: 'long' });
}
function dayNumber(cell: CalendarGridDay): string {
  return formatNumber(cell.date.day, localePack.value.defaultNumerals, localePack.value.digits);
}
</script>

<template>
  <div :dir="localePack.direction" data-jalali-calendar-root :data-jalali-calendar-view="view">
    <template v-if="view === 'day'">
      <div data-jalali-calendar-header>
        <button
          type="button"
          data-jalali-calendar-nav="previous"
          :aria-label="localePack.ui.previousMonth"
          @click="goPrevious"
        >
          ‹
        </button>
        <div data-jalali-calendar-title>
          <component
            :is="titleTag"
            :type="quickNav ? 'button' : undefined"
            data-jalali-calendar-title-month
            :aria-label="quickNav ? localePack.ui.chooseMonth : undefined"
            @click="openMonthView"
          >
            {{ monthLabel }}
          </component>
          <component
            :is="titleTag"
            :type="quickNav ? 'button' : undefined"
            data-jalali-calendar-title-year
            :aria-label="quickNav ? localePack.ui.chooseYear : undefined"
            @click="openYearView"
          >
            {{ yearLabel }}
          </component>
        </div>
        <button
          type="button"
          data-jalali-calendar-nav="next"
          :aria-label="localePack.ui.nextMonth"
          @click="goNext"
        >
          ›
        </button>
      </div>
      <div role="grid" data-jalali-calendar-grid>
        <div role="row" data-jalali-calendar-weekdays>
          <span
            v-for="(name, index) in weekdayLabelsForGrid(localePack.weekdayNames.short, system)"
            :key="index"
            role="columnheader"
            data-jalali-calendar-weekday
          >
            {{ name }}
          </span>
        </div>
        <div
          v-for="(week, weekIndex) in weeks"
          :key="weekIndex"
          role="row"
          data-jalali-calendar-week
        >
          <slot
            v-for="cell in week"
            :key="`${cell.date.year}-${cell.date.month}-${cell.date.day}`"
            name="day"
            :cell="cell"
            :select="selectDay"
          >
            <button
              type="button"
              role="gridcell"
              data-jalali-calendar-day
              :data-selected="cell.isSelected ? '' : undefined"
              :data-today="cell.isToday ? '' : undefined"
              :data-outside-month="cell.isCurrentMonth ? undefined : ''"
              :data-disabled="cell.isSelectable ? undefined : ''"
              :data-holiday="cell.isHoliday ? '' : undefined"
              :disabled="!cell.isSelectable"
              :aria-selected="cell.isSelected"
              :aria-current="cell.isToday ? 'date' : undefined"
              :aria-label="dayLabel(cell)"
              @click="selectDay(cell.date)"
            >
              {{ dayNumber(cell) }}
            </button>
          </slot>
        </div>
      </div>
    </template>

    <template v-else-if="view === 'month'">
      <div data-jalali-calendar-header>
        <button
          type="button"
          data-jalali-calendar-nav="previous"
          :aria-label="localePack.ui.previousYear"
          @click="goPreviousYearInMonthView"
        >
          ‹
        </button>
        <div data-jalali-calendar-title>
          <component
            :is="titleTag"
            :type="quickNav ? 'button' : undefined"
            data-jalali-calendar-title-year
            :aria-label="quickNav ? localePack.ui.chooseYear : undefined"
            @click="openYearView"
          >
            {{ yearLabel }}
          </component>
        </div>
        <button
          type="button"
          data-jalali-calendar-nav="next"
          :aria-label="localePack.ui.nextYear"
          @click="goNextYearInMonthView"
        >
          ›
        </button>
      </div>
      <div role="listbox" :aria-label="localePack.ui.month" data-jalali-calendar-months>
        <button
          v-for="item in months"
          :key="item.name"
          type="button"
          role="option"
          data-jalali-calendar-month
          :data-selected="item.isSelected ? '' : undefined"
          :data-today="item.isCurrent ? '' : undefined"
          :aria-selected="item.isSelected"
          :aria-current="item.isCurrent ? 'true' : undefined"
          @click="pickMonth(item.month)"
        >
          {{ item.name }}
        </button>
      </div>
    </template>

    <template v-else>
      <div data-jalali-calendar-header>
        <button
          type="button"
          data-jalali-calendar-nav="previous"
          :aria-label="localePack.ui.previousYears"
          @click="goPreviousYearPage"
        >
          ‹
        </button>
        <span data-jalali-calendar-title>{{ yearPageLabel }}</span>
        <button
          type="button"
          data-jalali-calendar-nav="next"
          :aria-label="localePack.ui.nextYears"
          @click="goNextYearPage"
        >
          ›
        </button>
      </div>
      <div role="listbox" :aria-label="localePack.ui.year" data-jalali-calendar-years>
        <button
          v-for="item in years"
          :key="item.year"
          type="button"
          role="option"
          data-jalali-calendar-year
          :data-selected="item.isSelected ? '' : undefined"
          :data-today="item.isCurrent ? '' : undefined"
          :aria-selected="item.isSelected"
          :aria-current="item.isCurrent ? 'true' : undefined"
          @click="pickYear(item.year)"
        >
          {{ item.label }}
        </button>
      </div>
    </template>
  </div>
</template>

// packages/react/src/Calendar.tsx
import { resolveCalendarHolidays, type HolidayRegion } from '@jalali-js/holidays';
import { format as formatDate, formatNumber } from '@jalali-js/i18n';
import type { CalendarDate, CalendarSystem, SelectionRules } from 'jalali-js';
import {
  buildCalendarGrid,
  createCalendar,
  nextMonth,
  previousMonth,
  weekdayLabelsForGrid,
} from 'jalali-js';
import type { ReactNode } from 'react';
import { useMemo, useState } from 'react';
import type { LocaleCode } from './use-calendar.js';
import { localePackFor } from './use-calendar.js';

const YEARS_PER_PAGE = 12;

export interface CalendarProps {
  /** Which calendar system to display. Default: 'jalali'. */
  system?: CalendarSystem;
  /** Which language the month title and weekday headers read in. Default: 'en'. */
  locale?: LocaleCode;
  /** The selected date, or `null` for none. */
  value?: CalendarDate | null;
  onSelect?: (date: CalendarDate) => void;
  /** The year/month the grid opens on. Default: `value`'s month, or today's. */
  initialDisplayedMonth?: { year: number; month: number };
  /**
   * Let a person click the month or year in the header to jump straight to a month grid or a
   * year grid, instead of paging one month at a time. Default: true.
   */
  quickNav?: boolean | undefined;
  /**
   * Limits on what a person can select (see `isDateSelectable()` in `jalali-js`). Blocked
   * days render disabled, with a `data-disabled` attribute, and reject selection.
   */
  rules?: SelectionRules | undefined;
  /**
   * Mark official holidays with a `data-holiday` attribute. Jalali system only.
   * Uses `@jalali-js/holidays`. Default list is Iran (`holidayRegion: 'IR'`).
   */
  showHolidays?: boolean;
  /**
   * Also block holiday days through Phase 16 selection rules. Jalali system only.
   * Uses `@jalali-js/holidays`.
   */
  blockHolidays?: boolean;
  /**
   * Whose official holiday list to use. Default: `'IR'` (Iran). Afghanistan and
   * Tajikistan are planned region codes; they are not shipped yet.
   */
  holidayRegion?: HolidayRegion;
  className?: string;
}

type CalendarView = 'day' | 'month' | 'year';

function yearPageStart(year: number): number {
  return year - (((year % YEARS_PER_PAGE) + YEARS_PER_PAGE) % YEARS_PER_PAGE);
}

function TitlePart({
  as,
  dataAttr,
  ariaLabel,
  onClick,
  children,
}: {
  as: 'button' | 'span';
  dataAttr: 'data-jalali-calendar-title-month' | 'data-jalali-calendar-title-year';
  ariaLabel: string;
  onClick: () => void;
  children: ReactNode;
}) {
  if (as === 'span') {
    return <span {...{ [dataAttr]: '' }}>{children}</span>;
  }
  return (
    <button type="button" {...{ [dataAttr]: '' }} aria-label={ariaLabel} onClick={onClick}>
      {children}
    </button>
  );
}

/**
 * A headless month grid: it renders plain markup with data attributes (`data-selected`,
 * `data-today`, `data-outside-month`, `data-disabled`, `data-holiday`) and no required CSS, so a
 * consumer can restyle it completely. `DatePicker` is this same component with a default
 * stylesheet and a popover wrapped around it.
 *
 * Days blocked by `rules` render as disabled buttons: clicks do nothing and the Tab order
 * skips them, so keyboard navigation skips blocked days. With `showHolidays`, holiday days
 * get `data-holiday`. With `blockHolidays`, those days also become unselectable.
 *
 * With `quickNav` (default on), clicking the month or year in the header opens a month grid or
 * a year grid, so a person can jump years ahead without paging one month at a time. Picking a
 * year moves to the month grid; picking a month moves to the day grid.
 */
export function Calendar({
  system = 'jalali',
  locale = 'en',
  value = null,
  onSelect,
  initialDisplayedMonth,
  quickNav = true,
  rules,
  showHolidays = false,
  blockHolidays = false,
  holidayRegion = 'IR',
  className,
}: CalendarProps) {
  const localePack = useMemo(() => localePackFor(locale), [locale]);
  const today = useMemo(() => createCalendar({ system }).today(), [system]);
  const [displayed, setDisplayed] = useState(
    () =>
      initialDisplayedMonth ??
      (value ? { year: value.year, month: value.month } : { year: today.year, month: today.month }),
  );
  const [view, setView] = useState<CalendarView>('day');
  const [yearPage, setYearPage] = useState(() => yearPageStart(displayed.year));

  const holidayOptions = useMemo(
    () =>
      resolveCalendarHolidays(system, displayed.year, displayed.month, {
        showHolidays,
        blockHolidays,
        region: holidayRegion,
        rules,
      }),
    [system, displayed.year, displayed.month, showHolidays, blockHolidays, holidayRegion, rules],
  );

  const weeks = useMemo(
    () =>
      buildCalendarGrid(
        system,
        displayed.year,
        displayed.month,
        today,
        value,
        holidayOptions.rules,
        holidayOptions.isHolidayDay,
      ),
    [system, displayed.year, displayed.month, today, value, holidayOptions],
  );

  const monthLabel = localePack.monthNames[system].long[displayed.month - 1];
  const yearLabel = formatNumber(displayed.year, localePack.defaultNumerals, localePack.digits);
  const titleAs = quickNav ? 'button' : 'span';

  function openMonthView(): void {
    setView('month');
  }
  function openYearView(): void {
    setYearPage(yearPageStart(displayed.year));
    setView('year');
  }
  function pickMonth(month: number): void {
    setDisplayed((current) => ({ ...current, month }));
    setView('day');
  }
  function pickYear(year: number): void {
    setDisplayed((current) => ({ ...current, year }));
    setView('month');
  }

  return (
    <div
      className={className}
      dir={localePack.direction}
      data-jalali-calendar-root
      data-jalali-calendar-view={view}
    >
      {view === 'day' && (
        <>
          <div data-jalali-calendar-header>
            <button
              type="button"
              data-jalali-calendar-nav="previous"
              aria-label={localePack.ui.previousMonth}
              onClick={() => setDisplayed(previousMonth(system, displayed.year, displayed.month))}
            >
              ‹
            </button>
            <div data-jalali-calendar-title>
              <TitlePart
                as={titleAs}
                dataAttr="data-jalali-calendar-title-month"
                ariaLabel={localePack.ui.chooseMonth}
                onClick={openMonthView}
              >
                {monthLabel}
              </TitlePart>
              <TitlePart
                as={titleAs}
                dataAttr="data-jalali-calendar-title-year"
                ariaLabel={localePack.ui.chooseYear}
                onClick={openYearView}
              >
                {yearLabel}
              </TitlePart>
            </div>
            <button
              type="button"
              data-jalali-calendar-nav="next"
              aria-label={localePack.ui.nextMonth}
              onClick={() => setDisplayed(nextMonth(system, displayed.year, displayed.month))}
            >
              ›
            </button>
          </div>
          <div role="grid" data-jalali-calendar-grid>
            <div role="row" data-jalali-calendar-weekdays>
              {weekdayLabelsForGrid(localePack.weekdayNames.short, system).map((name, index) => (
                <span key={index} role="columnheader" data-jalali-calendar-weekday>
                  {name}
                </span>
              ))}
            </div>
            {weeks.map((week, weekIndex) => (
              <div key={weekIndex} role="row" data-jalali-calendar-week>
                {week.map((cell) => (
                  <button
                    key={`${cell.date.year}-${cell.date.month}-${cell.date.day}`}
                    type="button"
                    role="gridcell"
                    data-jalali-calendar-day
                    data-selected={cell.isSelected ? '' : undefined}
                    data-today={cell.isToday ? '' : undefined}
                    data-outside-month={cell.isCurrentMonth ? undefined : ''}
                    data-disabled={cell.isSelectable ? undefined : ''}
                    data-holiday={cell.isHoliday ? '' : undefined}
                    disabled={!cell.isSelectable}
                    aria-selected={cell.isSelected}
                    aria-current={cell.isToday ? 'date' : undefined}
                    aria-label={formatDate(cell.date, localePack, { style: 'long' })}
                    onClick={() => onSelect?.(cell.date)}
                  >
                    {formatNumber(cell.date.day, localePack.defaultNumerals, localePack.digits)}
                  </button>
                ))}
              </div>
            ))}
          </div>
        </>
      )}

      {view === 'month' && (
        <>
          <div data-jalali-calendar-header>
            <button
              type="button"
              data-jalali-calendar-nav="previous"
              aria-label={localePack.ui.previousYear}
              onClick={() => setDisplayed((current) => ({ ...current, year: current.year - 1 }))}
            >
              ‹
            </button>
            <div data-jalali-calendar-title>
              <TitlePart
                as={titleAs}
                dataAttr="data-jalali-calendar-title-year"
                ariaLabel={localePack.ui.chooseYear}
                onClick={openYearView}
              >
                {yearLabel}
              </TitlePart>
            </div>
            <button
              type="button"
              data-jalali-calendar-nav="next"
              aria-label={localePack.ui.nextYear}
              onClick={() => setDisplayed((current) => ({ ...current, year: current.year + 1 }))}
            >
              ›
            </button>
          </div>
          <div role="listbox" aria-label={localePack.ui.month} data-jalali-calendar-months>
            {localePack.monthNames[system].long.map((name, index) => {
              const month = index + 1;
              const isSelected = displayed.month === month;
              const isCurrent = today.year === displayed.year && today.month === month;
              return (
                <button
                  key={name}
                  type="button"
                  role="option"
                  data-jalali-calendar-month
                  data-selected={isSelected ? '' : undefined}
                  data-today={isCurrent ? '' : undefined}
                  aria-selected={isSelected}
                  aria-current={isCurrent ? 'true' : undefined}
                  onClick={() => pickMonth(month)}
                >
                  {name}
                </button>
              );
            })}
          </div>
        </>
      )}

      {view === 'year' && (
        <>
          <div data-jalali-calendar-header>
            <button
              type="button"
              data-jalali-calendar-nav="previous"
              aria-label={localePack.ui.previousYears}
              onClick={() => setYearPage((current) => current - YEARS_PER_PAGE)}
            >
              ‹
            </button>
            <span data-jalali-calendar-title>
              {formatNumber(yearPage, localePack.defaultNumerals, localePack.digits)}
              {' – '}
              {formatNumber(
                yearPage + YEARS_PER_PAGE - 1,
                localePack.defaultNumerals,
                localePack.digits,
              )}
            </span>
            <button
              type="button"
              data-jalali-calendar-nav="next"
              aria-label={localePack.ui.nextYears}
              onClick={() => setYearPage((current) => current + YEARS_PER_PAGE)}
            >
              ›
            </button>
          </div>
          <div role="listbox" aria-label={localePack.ui.year} data-jalali-calendar-years>
            {Array.from({ length: YEARS_PER_PAGE }, (_, index) => yearPage + index).map((year) => {
              const isSelected = displayed.year === year;
              const isCurrent = today.year === year;
              return (
                <button
                  key={year}
                  type="button"
                  role="option"
                  data-jalali-calendar-year
                  data-selected={isSelected ? '' : undefined}
                  data-today={isCurrent ? '' : undefined}
                  aria-selected={isSelected}
                  aria-current={isCurrent ? 'true' : undefined}
                  onClick={() => pickYear(year)}
                >
                  {formatNumber(year, localePack.defaultNumerals, localePack.digits)}
                </button>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
